export const comicData = [
  {
    id: 1,
    hero: "Dr. Doom",
    name: "Victor von Doom",
    link: "http://marvel.com/characters/13/dr_doom",
    img: "https://i.annihil.us/u/prod/marvel/i/mg/f/c0/6035276e100f2/clean.jpg",
    size: 40000,
  },
  {
    id: 2,
    hero: "Ronan",
    name: "Ronan",
    link: "http://marvel.com/characters/49/ronan",
    img: "https://i1.whakoom.com/large/2e/31/d7314bee70f8490a98f05d561e31c528.jpg",
    size: 40000,
  },
  {
    id: 3,
    hero: "Magneto",
    name: "Max Eisenhardt",
    link: "http://marvel.com/characters/35/magneto",
    img: "https://i.annihil.us/u/prod/marvel/i/mg/7/03/61426068ad880/clean.jpg",
    size: 40000,
  },
  {
    id: 4,
    hero: "Thanos",
    name: "Thanos",
    link: "http://marvel.com/characters/58/thanos",
    img: "https://i.annihil.us/u/prod/marvel/i/mg/b/f0/5a6111deb8b7c/clean.jpg",
    size: 40000,
  },
  {
    id: 5,
    hero: "Black Cat",
    name: "Felicia Hardy",
    link: "http://marvel.com/characters/271/black_cat",
    img: "https://i.annihil.us/u/prod/marvel/i/mg/f/60/614b4011d5072/clean.jpg",
    size: 40000,
  },
  {
    id: 6,
    hero: "Daredevil",
    name: "Daredevil",
    link: "http://marvel.com/characters/49/ronan",
    img: "https://i.annihil.us/u/prod/marvel/i/mg/c/30/62b9e04dbaa95/clean.jpg",
    size: 40000,
  },
];
